version: '3.7'
services:
  es:
    build:
      context: ./elasticsearch/.
      args:
        ELK_VERSION: 7.15.2
    container_name: elasticsearch
    environment:
      - node.name=nengtul-node
      - cluster.name=nengtul-cluster
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200/
    ports:
      - "5601:5601"
    depends_on:
      - es
    networks:
      - es-bridge


#  filebeat:
#    container_name: filebeat
#    image: docker.elastic.co/beats/filebeat:7.6.2
#    volumes:
#      - ./filebeat/filebeat-eslog.yml:/usr/share/filebeat/filebeat-eslog.yml
#    ports:
#      - 5044:5044
#    depends_on:
#      - elasticsearch
#    networks:
#      - es-bridge

#  logstash:
#    container_name: logstash
#    image: docker.elastic.co/logstash/logstash:7.6.2
#    environment:
#      ELASTICSEARCH_HOSTS: http://es:9200
#      ELASTIC_PASSWORD: ${ES_PASSWORD}
#    ports:
#      - 5044:5044
#    depends_on:
#      - elasticsearch
#    networks:
#      - es-bridge

networks:
  es-bridge:
    driver: bridge