spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  elasticsearch:
    uris: ${ES_URI}
    password: ${ES_PASSWORD}
    username: ${ES_USER_NAME}
  batch:
    job:
      enabled: true
      name: crawlingJob
    jdbc:
      initialize-schema: always
server:
  port: 8081
